version: 2.1
orbs:
  terraform: circleci/terraform@2.1.0  

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:0.14.3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD    

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &install-dependencies
    run:
      name: Install dependencies
      command: |
        mkdir -p artifacts
        # sudo -i
        apt-get -y -qq update
        apt-get install -y awscli
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        apt-get install terraform build-essential -y
        apt install gettext-base moreutils -y
      
jobs:
  terraform-init-validate-plan-apply:
    executor: terraform-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *install-dependencies
      - run:
          name: Copy Infrastructure Folder
          command: |
            cp -r infrastructure artifacts/infrastructure
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - run:
          name: Terraform Validate & Format
          command: |
            cd infrastructure/
            terraform init -backend=false
            terraform workspace select ${CIRCLE_BRANCH} || terraform workspace new ${CIRCLE_BRANCH}
            terraform validate
            # terraform fmt -check
      - run:                  
          name: Terraform Plan & Apply
          command: |            
            terraform plan
            terraform apply --auto-approve
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

  terraform-destroy:
    executor: terraform-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./      
      - *show-current-branch-name
      - *install-dependencies      
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc            
      - run:
          name: Terraform Destroy
          command: |
            cd infrastructure/
            terraform init
            terraform workspace select ${CIRCLE_BRANCH} || terraform workspace new ${CIRCLE_BRANCH}
            terraform destroy --auto-approve
workflows:
  deploy_test_infra:
    jobs:      
      - terraform-init-validate-plan-apply:
          filters:
            branches:
              only:
                - infra-test
      - terraform-destroy:
          requires:
            - terraform-init-validate-plan-apply
          filters:
            branches:
              only:
                - infra-test

